# Generated by Django 4.2.23 on 2025-06-14 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSyncStatus',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='email_sync_status', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_in_progress', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(db_index=True, max_length=255)),
                ('thread_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.TextField()),
                ('subject', models.TextField()),
                ('snippet', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('is_read', models.BooleanField(default=False)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('raw_headers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
                'unique_together': {('user', 'gmail_message_id')},
            },
        ),
    ]
